#
# Build
#

build { core init app/noux-pkg/ocaml }

create_boot_directory

#
# Generate config
#

install_config {
<config>
	<parent-provides>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<start name="hello_server">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Hello"/> </provides>
	</start>
	<start name="hello_client">
		<resource name="RAM" quantum="1M"/>
	</start>
</config>}

#
# Build boot image
#

build_boot_image { core init ocaml }
